name: 'download-artifact'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    # You can uncomment the line below to use environments (refer to https://docs.github.com/en/actions/reference/environments). 
    #environment: test_environment
    env:
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.M365_TENANT_ID}}
      # To specify the env name for multi-env feature.
      TEAMSFX_ENV_NAME: dev

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: install github cli
      run: |
        sudo apt update
        sudo apt install gh
    
    - name: get CD run id
      run: |
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  -q '[.workflow_runs[] | {name,workflow_id,artifacts_url}] | .[] | select(.name=="CD")'  /repos/officedev/teamsfx/actions/runs >> run_id.json
        cat run_id.json


