name: 'download-artifact'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    # You can uncomment the line below to use environments (refer to https://docs.github.com/en/actions/reference/environments). 
    #environment: test_environment
    env:
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.M365_TENANT_ID}}
      # To specify the env name for multi-env feature.
      TEAMSFX_ENV_NAME: dev

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      id: download
      with:
        name: 'my-artifact'
        path: /repos/officedev/teamsfx/actions/artifacts/594375111/zip

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
